import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Material Design 3 tokens — Elis brand green palette
        'surface':                    '#f5fdf5',
        'surface-bright':             '#f5fdf5',
        'surface-dim':                '#cad5cb',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#eef7ef',
        'surface-container':          '#e6f0e7',
        'surface-container-high':     '#daeada',
        'surface-container-highest':  '#cde3ce',
        'surface-variant':            '#d4e8d4',
        'on-surface':                 '#0d1f10',
        'on-surface-variant':         '#3a4a3c',
        'outline':                    '#6b7b6d',
        'outline-variant':            '#b8d4ba',
        'inverse-surface':            '#1a2e1c',
        'inverse-on-surface':         '#ecf4ed',
        'background':                 '#f5fdf5',
        'on-background':              '#0d1f10',
        // Primary — deep forest green
        'primary':                    '#4a7355',
        'primary-container':          '#5f8a67',
        'primary-fixed':              '#d4edd4',
        'primary-fixed-dim':          '#b5d4b5',
        'on-primary':                 '#ffffff',
        'on-primary-container':       '#f0faf0',
        'on-primary-fixed':           '#041208',
        'on-primary-fixed-variant':   '#1e4a28',
        'inverse-primary':            '#a0c8a8',
        'surface-tint':               '#4a7355',
        // Secondary — sage green
        'secondary':                  '#6b9e72',
        'secondary-container':        '#c8e3c8',
        'secondary-fixed':            '#ccebcc',
        'secondary-fixed-dim':        '#aacbaa',
        'on-secondary':               '#ffffff',
        'on-secondary-container':     '#2a4e2e',
        'on-secondary-fixed':         '#052008',
        'on-secondary-fixed-variant': '#1e4020',
        // Tertiary — warm neutral
        'tertiary':                   '#6b7b5a',
        'tertiary-container':         '#8a9a72',
        'tertiary-fixed':             '#e4eadd',
        'tertiary-fixed-dim':         '#c8d0bc',
        'on-tertiary':                '#ffffff',
        'on-tertiary-container':      '#f5faf0',
        'on-tertiary-fixed':          '#1b2018',
        'on-tertiary-fixed-variant':  '#424d38',
        // Error
        'error':                      '#ba1a1a',
        'error-container':            '#ffdad6',
        'on-error':                   '#ffffff',
        'on-error-container':         '#93000a',
      },
      spacing: {
        'section-desktop': '80px',
        'section-mobile': '48px',
        'gutter': '24px',
        'container-max': '1200px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        'full': '9999px',
      },
      fontFamily: {
        sans:      ['Atkinson Hyperlegible Next', 'system-ui', 'sans-serif'],
        headline:  ['Montserrat', 'system-ui', 'sans-serif'],
        label:     ['Manrope', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg':        ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.25', fontWeight: '600' }],
        'headline-md':       ['32px', { lineHeight: '1.3', fontWeight: '500' }],
        'headline-sm':       ['24px', { lineHeight: '1.35', fontWeight: '500' }],
        'body-lg':           ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md':           ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md':          ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '600' }],
        'caption':           ['12px', { lineHeight: '1.4', fontWeight: '400' }],
      },
      maxWidth: {
        'container': '1200px',
      },
      boxShadow: {
        'ambient':    '0 8px 24px -4px rgba(74, 115, 85, 0.08), 0 2px 8px -2px rgba(74, 115, 85, 0.04)',
        'ambient-md': '0 16px 40px -8px rgba(74, 115, 85, 0.12), 0 4px 12px -4px rgba(74, 115, 85, 0.06)',
        'sm':         '0 1px 3px 0 rgba(74, 115, 85, 0.08)',
      },
      animation: {
        'fade-in':  'fadeIn 0.6s ease-out forwards',
        'slide-up': 'slideUp 0.6s ease-out forwards',
      },
      keyframes: {
        fadeIn:  { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { opacity: '0', transform: 'translateY(24px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
      },
    },
  },
  plugins: [],
} satisfies Config
